title: Mikhail Hoskins
logo: assets/img/linkedin_photo_2.jpg
description: Data scientist focused on public health and epidemiology, with experience building reproducible analytics workflows and modeling processes in SAS, R, and SQL.
show_downloads: true
theme: jekyll-theme-minimal
