title: Mikhail Hoskins
description: Data scientist focused on public health and epidemiology, with experience building reproducible analytics workflows and modeling processes primarily in SQL, SAS, and R (with more and more Python).
theme: jekyll-theme-minimal
baseurl: /test_pages
logo: https://raw.githubusercontent.com/mishahoskins/test_pages/main/git_photo_2.png
show_downloads: true
